<table id="documentos-normativa" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>PDF</th>
      <th>Documento</th>
      <th>Usuario ISO</th>
      <th>Versión</th>
      <th>Fecha_Carga</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>PDF</th>
      <th>Documento</th>
      <th>Usuario ISO</th>
      <th>Versión</th>
      <th>Fecha_Carga</th>
    </tr>
  </tfoot>
  <tbody>
 <tr> <td><a href="http://sistema.mobagricola.cl/assets/documentos/PA-G-2 Mantención.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PA-G-2 Mantención.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/PA-G-2.1 Procedimiento de Mantenimiento preventivo.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PA-G-2.1 Procedimiento de Mantenimiento preventivo.pdf  </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PLA-G-2.1 Plan de Mantenimiento Preventivo Servicios Generales.pdf  </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/PLA-G-2.2 Plan de Mantenimiento Preventivo a Equipos producción.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PLA-G-2.2 Plan de Mantenimiento Preventivo a Equipos producción.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PLA-G-2.3 Plan de Mantenimiento Preventivo Agrícola.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PLA-G-2.4 Programa Gato electronico.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PLA-G-2.5 Plan de mantenimiento preventivo FA.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  PLA-G-2.6 Plan de mantenimiento preventivo Maquina Compostadora.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-2.7 Orden de trabajo.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-2.8 Registro de Mantención.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento3.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento4.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento1.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>
<tr>  <td><a href="http://sistema.mobagricola.cl/assets/documentos/Template.pdf" target="_blank" style="border:0px solid transparent;color:red;border-color:red;margin-left: 2px;"><img alt="document, pdf icon" class="tiled-icon" style="max-width: 128px; max-height: 128px;" src="http://compras.mobagricola.cl/assets/images/document-pdf.png" data-pin-nopin="true"></a></td>  <td>  RA-G-0.0 Documento2.pdf </td> <td>usuario1</td> <td>1.1</td>  <td>01/01/2017</td> </tr>


 </tbody>
</table>